name: eslint action
on: 
  push: 
    branches: 
      - development
jobs:
    eslint: 
      runs-on: ubuntu-latest
      steps: 
        - name:  checkout action
          uses : actions/checkout@v3
        - name: install dependecies
          run: npm install 
        - name: init eslint
          run: npm run lint
