name: eslint action
on: 
  push: 
    branches: 
      - development
jobs:
    eslint: 
      runs-on: ubuntu-latest
      steps: 
        - name:  checkout action
          uses : actions/checkout@v3
        - name: install dependecies
          run: npm install 
        - name: init eslint
          id: eslint
          run: npm run lint
        - name: Annotate Code Linting Results
          uses: ataylorme/eslint-annotate-action@1.0.4
          if: always()
          with:
            repo-token: '${{ secrets.GITHUB_TOKEN }}'
            report-json: 'eslint_report.json'