name: eslint action
on: 
  push: 
    branches: 
      - development
jobs:
    eslint: 
      runs-on: ubuntu-latest
      steps: 
        - name:  checkout action
          uses : actions/checkout@v3
        - name: install dependecies
          run: npm install 
        - name: init eslint
          id: eslint
          run: npm run lint
        - name: Merge by labeled
          uses: devmasx/merge-branch@master
          with:
            type: now 
            from_branch: Production
            target_branch: development
            github_token: ${{ github.token }}